version: "3.7"

services:
  prisma:
    image: petitloan/appointment_scheduler:prisma
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.prisma.loadbalancer.server.port=4000"
        - "traefik.http.routers.prisma.rule=HostRegexp(`{host:(?:www.)?appointment-scheduler.loanpetit.com}`)"
        - "traefik.http.routers.prisma.entrypoints=prisma"
        - "traefik.http.routers.prisma.tls.certresolver=default"
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
